### ISSUE TITLE
is it possible to define an image to load for use in the sparkle effect?

### ISSUE THREAD

**Issue by starpause** [simeydotme/jQuery-canvas-sparkles#4]
I tried base 64 encoding my own PNG and dropping it in place of the data:image/png;base64 in the source but the result is no sparkles instead of a new sparkle image. Thanks for any ideas!
![sparkle-star](https://cloud.githubusercontent.com/assets/408953/6473960/ec3ba8e4-c1b1-11e4-83a5-7bcea8c2a9fc.png)

**Comment by simeydotme** [comment]
I did consider this before...
however it will require a lot of work due to the calculations for the sprite rotation and such... also replacing it as a external file wouldn't work either because I don't use a load event (base64 needs no loading) ... 

I will think about it, but for now your best bet is to try and replace the base64 with another base64 sprite with the exact same dimensions :)

Best of luck, Simon.
